spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdemodb
    username: root
    password:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  jpa:
    hibernate:
      ddl-auto: none